
alias relog='exec $SHELL -l'
alias ls='ls --color=auto'
alias ll='ls -al --color | less -R'
alias ssx='ssh -XC'
alias stl='systemctl'
alias tmux='tmux -2'
alias opn='xdg-open'
alias mv='mv -i'
alias d='docker'
alias gn='geeknote'
alias nv='nvim'
alias ca='cargo'

alias ad='git add'
alias br='git branch'
alias co='git checkout'
alias cl='git clone'
alias ci='git commit'
alias di='git diff'
alias fe='git fetch'
alias lgg='git log --color --all --graph --decorate'
alias mgf='git merge --ff-only'
alias pu='git push'
alias re='git remote'
alias rp='git rev-parse'
alias rpr='git rev-parse --show-toplevel'
alias sa='git stash'
alias so='git show'
alias st='git status'
