[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
  nnoremap [Denite] <Nop>
  nmap <silent><space> [Denite]
  nnoremap [Denite]f :<c-u>Denite file_rec<CR>
  nnoremap [Denite]m :<c-u>Denite file_mru<CR>
  nnoremap [Denite]/ :<c-u>Denite line<CR>
  nnoremap [Denite]g :<c-u>Denite grep<CR>
  nnoremap [Denite]r :<c-u>Denite -resume<CR>
  call denite#custom#map('insert', '<c-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<c-p>', '<denite:move_to_previous_line>', 'noremap')
  call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('normal', 'dd', '<denite:delete_entire_text>', 'noremap')
  call denite#custom#map('normal', 'h', '<denite:move_caret_to_left>', 'noremap')
  call denite#custom#map('normal', 'l', '<denite:move_caret_to_right>', 'noremap')
  call denite#custom#map('normal', 'b', '<denite:move_caret_to_one_word_left>', 'noremap')
  call denite#custom#map('normal', 'w', '<denite:move_caret_to_one_word_right>', 'noremap')
  call denite#custom#map('normal', 'x', '<denite:delete_char_before_caret>', 'noremap')
  call denite#custom#map('normal', '0', '<denite:move_caret_to_head>', 'noremap')
  call denite#custom#map('normal', '$', '<denite:move_caret_to_tail>', 'noremap')
  call denite#custom#map('normal', '<c-s>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('normal', '<c-v>', '<denite:do_action:vsplit>', 'noremap')
  call denite#custom#map('insert', '<c-s>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('insert', '<c-v>', '<denite:do_action:vsplit>', 'noremap')
'''
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add='''
  colorscheme solarized
  let g:solarized_termtrans=1
  let g:solarized_visibility="low"
  let g:solarized_termcolors=256
'''
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add='''
set completeopt+=noselect
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1
inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function() abort
  return deoplete#close_popup() . "\<CR>"
endfunction
'''
[[plugins]] # deoplete source from syntax highlight
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = './install.sh'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
  \ 'haskell': ['stack', 'exec', 'hie', '--', '--lsp'],
  \ 'python': ['pyls']}
'''
