[[plugins]] # markdown {{{
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
hook_add = '''
  let g:previm_open_cmd = 'firefox'
''' # }}}

[[plugins]] # vim {{{
repo = 'Shougo/neco-vim'
on_ft = 'vim'
# }}}

# vim: foldmethod=marker:
