[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'tpope/vim-surround'
hook_add='''
  colorscheme solarized
  let g:solarized_termtrans=1
  let g:solarized_visibility="low"
  let g:solarized_termcolors=256
'''
