[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'Shougo/neco-syntax'
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'octaltree/rustdoc-index'
build = 'make denite'
hook_add = '''
nnoremap <silent><space>s :<c-u>Denite rustdoc-index<CR>
'''

[[plugins]] # polyglot {{{
repo = 'sheerun/vim-polyglot'
hook_add='''
let g:polyglot_disabled = ['csv', 'markdown']
''' # }}}

[[plugins]] # treesitter {{{
repo = 'nvim-treesitter/nvim-treesitter'
build = 'TSUpdate' # }}}

[[plugins]] # solarized {{{
#repo = 'altercation/vim-colors-solarized'
repo = 'lifepillar/vim-solarized8'
hook_add='''
  "colorscheme solarized
  "let g:solarized_visibility="low"
  "let g:solarized_termcolors=256
  let g:solarized_termtrans=1
  autocmd VimEnter * nested colorscheme solarized8
  autocmd ColorScheme * hi Folded guifg=#839496 guibg=None guisp=#002b36 gui=None cterm=None
  autocmd ColorScheme * hi NormalFloat guibg=None
''' # }}}

[[plugins]] # whitespace {{{
repo = 'bronson/vim-trailing-whitespace'
hook_add='''
let g:extra_whitespace_ignored_filetypes=['denite']
autocmd BufRead,BufNewFile * if ShouldMatchWhitespace() | match ExtraWhitespace /\\\@<![\u3000[:space:]]\+$/ | else | match ExtraWhitespadce /^^/ | endif
''' # }}}

[[plugins]] # nerdcommenter {{{
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDDefaultAlign = 'left'
''' # }}}

[[plugins]] # vimproc {{{
repo = 'Shougo/vimproc.vim'
build = 'make'
# }}}

# vim: foldmethod=marker
