#[[plugins]]
#repo = 'Shougo/Unite.vim'
#on_cmd = 'Unite'
#hook_add='''
#let g:unite_enable_start_insert = 1
#'''
# web
[[plugins]]
repo  = 'othree/html5.vim'
on_ft = 'html'
#[[plugins]] # fold用syntaxあるけど重い
#repo  = 'othree/yajs.vim'
#on_ft = 'javascript'
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = 'javascript'
hook_post_update = '''
let g:dein#plugin.build = './install.sh'
'''
hook_source='''
let g:tigris#enabled = 1
let g:tigris#on_the_fly_enabled = 1
let g:tigris#delay = 300
'''
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact']
# toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'
# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''
# Tex
[[plugins]]
repo = 'poppyschmo/deoplete-latex'
on_ft = ['tex', 'latex']
# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add='''
let g:rustfmt_autosave = 1
set foldmethod=syntax
let g:rust_fold=1
'''
#[[plugins]]
#repo = 'racer-rust/vim-racer'
#on_ft = 'rust'
#hook_add='''
#let g:racer_experimental_completer = 1
#nmap gd <Plug>(rust-def)
#'''
[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'
hook_add='''
let g:rust_doc#downloaded_rust_doc_dir = '$HOME/.rustup/toolchains/stable-*'
"nnoremap <silent><space>s :<c-u>Unite rust/doc<CR>
nnoremap <silent><space>s :<c-u>Denite rust/doc<CR>
'''
#[[plugins]]
#repo = 'octaltree/rust-doc.vim'
#on_ft = 'rust'
#hook_add='''
#let g:rust_doc#downloaded_rust_doc_dir = '$HOME/.rustup/toolchains/stable-*'
#nnoremap <silent><space>s :<c-u>Denite rust/doc<CR>
#'''
# C/ C++
[[plugins]]
repo = 'https://github.com/zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''

[[plugins]]
repo = 'https://github.com/rupurt/vim-mql5'
on_ft = ['mq5', 'mql5']

# firenvim {{{
[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update='''
call firenvim#install(0)
'''
hook_add='''
let g:firenvim_config = {
    \ 'localSettings': {
        \ '.*': {
            \ 'selector': 'textarea, div[role="textbox"]',
            \ 'priority': 0,
        \ }
    \ }
\ }
augroup Firenvim
  au BufEnter play.golang.org_*.txt setlocal filetype=go
  au BufEnter play.rust-lang.org_*.txt setlocal filetype=rust
  au BufEnter github.com_*.txt setlocal filetype=markdown
  au BufEnter localhost*ipynb*.txt setlocal filetype=python
augroup END
'''
# }}}
